# Generated by Django 5.0.3 on 2024-03-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formvalidation',
            name='password',
            field=models.CharField(default=True, max_length=50, unique=True),
        ),
    ]
